<#
.SYNOPSIS
  Build-Policy-Directories.ps1 — regenerate each policy's "Decisions governed by this
  policy" table from the `Governing Policy:` line in every ADR. Generated, never hand-typed
  (POL-0004 applied to governance itself: the directory cannot drift).

.DESCRIPTION
  Run from the repo root (Atlas-Engineering-Repository). The script:
    1. Scans 00-Atlas-Foundation/Decisions/ADR-*.md for a "Governing Policy" value
       (a `| Governing Policy | ... |` metadata row, or a `Governing Policy:` line).
    2. For every POL-xxxx that value names, writes a row into that policy's
       AUTOGEN:decisions block in 00-Atlas-Foundation/Policies/POL-xxxx-*.md.
  Only content BETWEEN the markers is touched — hand-written prose is preserved.
  Idempotent (re-running with no ADR changes rewrites nothing). LF endings preserved.

  An ADR appears in a policy's directory only once it carries `Governing Policy: POL-xxxx`.
  Until the backfill sweep runs, most ADRs have no line and are skipped (by design).

.PARAMETER Root
  Repo root. Defaults to the current directory.

.EXAMPLE
  pwsh ./tools/Build-Policy-Directories.ps1            # regenerate all policy directories
  pwsh ./tools/Build-Policy-Directories.ps1 -WhatIf    # dry run — show what would change
#>
[CmdletBinding(SupportsShouldProcess)]
param([string]$Root = (Get-Location).Path)
$ErrorActionPreference = 'Stop'

$decDir = Join-Path $Root '00-Atlas-Foundation/Decisions'
$polDir = Join-Path $Root '00-Atlas-Foundation/Policies'
if (-not (Test-Path $decDir)) { throw "Not found: $decDir — run this from the repo root (Atlas-Engineering-Repository)." }

# ---- 1. Parse every ADR that carries a Governing Policy line ----
$rows = New-Object System.Collections.Generic.List[object]
Get-ChildItem -Path $decDir -Filter 'ADR-*.md' -File |
  Where-Object { $_.Name -ne 'ADR-Index.md' } | ForEach-Object {
    $file = $_.Name
    $text = Get-Content -LiteralPath $_.FullName -Raw
    if ($file -notmatch '^(ADR-\d{4})') { return }
    $id = $Matches[1]
    $title = if ($text -match '(?m)^\#\s+(.+?)\s*$') { $Matches[1].Trim() } else { $id }

    $gp = $null
    if     ($text -match '(?m)^\|\s*Governing Policy\s*\|\s*(.+?)\s*\|') { $gp = $Matches[1].Trim() }
    elseif ($text -match '(?m)^Governing Policy:\s*(.+?)\s*$')          { $gp = $Matches[1].Trim() }
    if ([string]::IsNullOrWhiteSpace($gp)) { return }   # no governing policy yet -> skip

    $status = ''
    if     ($text -match '(?m)^\|\s*Status\s*\|\s*(.+?)\s*\|') { $status = $Matches[1].Trim() }
    elseif ($text -match '(?m)^Status:\s*(.+?)\s*$')          { $status = $Matches[1].Trim() }
    $status = ($status -replace '\*\*','' -replace '`','').Trim()
    if ($status.Length -gt 60) { $status = $status.Substring(0,57) + [char]0x2026 }

    $short = ($title -replace '^ADR-\d{4}\s*[—:\-]\s*','').Trim()
    if ($short.Length -gt 60) { $short = $short.Substring(0,57) + [char]0x2026 }

    [regex]::Matches($gp,'POL-\d{4}') | ForEach-Object { $_.Value } | Sort-Object -Unique | ForEach-Object {
      $rows.Add([pscustomobject]@{
        Pol  = $_
        Id   = $id
        Line = "| [$id $([char]0x2014) $short](../Decisions/$file) | $status | $gp |"
      })
    }
  }

# ---- 2. Rewrite each policy's AUTOGEN block ----
$updated = @(); $skipped = @()
$rows | Group-Object Pol | ForEach-Object {
  $pol = $_.Name
  $pf  = Get-ChildItem -Path $polDir -Filter "$pol-*.md" -File | Select-Object -First 1
  if (-not $pf) { $skipped += "$pol (no policy file)"; return }

  $content = Get-Content -LiteralPath $pf.FullName -Raw
  $begin = "<!-- BEGIN AUTOGEN:decisions $pol"
  $endMk = "<!-- END AUTOGEN:decisions $pol -->"
  $si = $content.IndexOf($begin)
  $ei = if ($si -ge 0) { $content.IndexOf($endMk, $si) } else { -1 }
  if ($si -lt 0 -or $ei -lt 0) { $skipped += "$pol (no AUTOGEN:decisions block)"; return }
  $ei += $endMk.Length

  $block = @(
    "$begin " + [char]0x00B7 + " generated by tools/Build-Policy-Directories.ps1 — do not hand-edit -->",
    "| Decision | Status | Governing Policy |",
    "|---|---|---|"
  ) + ($_.Group | Sort-Object Id | ForEach-Object { $_.Line }) + @($endMk)

  $new = $content.Substring(0,$si) + ($block -join "`n") + $content.Substring($ei)
  $new = $new -replace "`r`n","`n"   # enforce LF

  if ($new -ne $content) {
    if ($PSCmdlet.ShouldProcess($pf.Name, "regenerate $($_.Count) decision row(s)")) {
      [System.IO.File]::WriteAllText($pf.FullName, $new)
    }
    $updated += "$pol ($($_.Count))"
  }
}

Write-Host ("Updated: " + $(if ($updated) { $updated -join ', ' } else { '(none)' }))
if ($skipped) { Write-Warning ("Skipped: " + ($skipped -join ', ')) }
